"""File for Compass Wifi client models."""
from dataclasses import dataclass

@dataclass
class Device:
    """Class for a device."""
    id: str
    unique_key: str
    name: str
    description: str
    model_name: str
    zipcode: str
    owned: str
    owner: str
    online: str
    groups: list[str]

class DeviceState:
    CF: int
    DF1: int
    DF2: int
    DF3: int
    STOF: int
    DB: int
    HTS: int
    DFG: int
    DFU: int
    DFL: int
    AXD: int
    LKO: int
    MXH: int
    MNH: int
    VC: int
    VH: int
    CAL: int
    CYC: int
    SEN: int
    PSP: int
    HRO: int
    HUDE: int
    HUDI: int
    HUOP: int
    HUAC: int
    HUNC: int
    RSV1: int
    RSV2: int
    RSV3: int
    FLT: int
    RSFL: int
    RSWF: int
    MD: int
    FAN: int
    SCH: int
    EMH: int
    CST: int
    HST: int
    LKD: int
    LHS: int
    LCS: int
    F100H: int
    F1H: int
    HUST: int
    VACST: int
    VACSY: int
    VACSM: int
    VACSD: int
    VACSH: int
    VACSMI: int
    VACEY: int
    VACEM: int
    VACED: int
    VACEH: int
    VACEMI: int
    OUTST: int
    MWH: int
    MWM: int
    MWC: int
    MWHT: int
    MLH: int
    MLM: int
    MLC: int
    MLHT: int
    MRH: int
    MRM: int
    MRC: int
    MRHT: int
    MSH: int
    MSM: int
    MSC: int
    MSHT: int
    TWH: int
    TWM: int
    TWC: int
    TWHT: int
    TLH: int
    TLM: int
    TLC: int
    TLHT: int
    TRH: int
    TRM: int
    TRC: int
    TRHT: int
    TSH: int
    TSM: int
    TSC: int
    TSHT: int
    WWH: int
    WWM: int
    WWC: int
    WWHT: int
    WLH: int
    WLM: int
    WLC: int
    WLHT: int
    WRH: int
    WRM: int
    WRC: int
    WRHT: int
    WSH: int
    WSM: int
    WSC: int
    WSHT: int
    THWH: int
    THWM: int
    THWC: int
    THWHT: int
    THLH: int
    THLM: int
    THLC: int
    THLHT: int
    THRH: int
    THRM: int
    THRC: int
    THRHT: int
    THSH: int
    THSM: int
    THSC: int
    THSHT: int
    FWH: int
    FWM: int
    FWC: int
    FWHT: int
    FLH: int
    FLM: int
    FLC: int
    FLHT: int
    FRH: int
    FRM: int
    FRC: int
    FRHT: int
    FSH: int
    FSM: int
    FSC: int
    FSHT: int
    SAWH: int
    SAWM: int
    SAWC: int
    SAWHT: int
    SALH: int
    SALM: int
    SALC: int
    SALHT: int
    SARH: int
    SARM: int
    SARC: int
    SARHT: int
    SASH: int
    SASM: int
    SASC: int
    SASHT: int
    SUWH: int
    SUWM: int
    SUWC: int
    SUWHT: int
    SULH: int
    SULM: int
    SULC: int
    SULHT: int
    SURH: int
    SURM: int
    SURC: int
    SURHT: int
    SUSH: int
    SUSM: int
    SUSC: int
    SUSHT: int
    WCT: int
    WCH: int
    WCC: int
    W1H: int
    W1L: int
    W1C: int
    W2H: int
    W2L: int
    W2C: int
    W3H: int
    W3L: int
    W3C: int
    GEN0: int
    GEN1: int
    GEN2: int
    GEN3: int
    GEN4: int
    GEN5: int
    GEN6: int
    GEN7: int
    GEN8: int
    GEN9: int
    GEN10: int
    GEN11: int
    GEN12: int
    GEN13: int
    GEN14: int
    GEN15: int
    GEN16: int
    GEN17: int
    RMT: int
    RMH: int
    CHGF: int
    MODEL1: int
    MODEL2: int
    MODEL3: int
    MODEL4: int
    MODEL5: int
    MODEL6: int
    MODEL7: int
    MODEL8: int
    MODEL9: int
    MODEL10: int
    MAC1: int
    MAC2: int
    MAC3: int
    MAC4: int
    MAC5: int
    MAC6: int
    MAC7: int
    MAC8: int
    MAC9: int
    MAC10: int
    MAC11: int
    MAC12: int

@dataclass
class DeviceDetail:
    id: str
    unique_key: str
    name: str
    description: str
    model_id: str
    zipcode: str
    last_online: str
    server_time: str
    currentState: DeviceState

    def from_json(device_dict):
        device_state_dict = device_dict.pop('state', None)
        device = DeviceDetail(**device_dict)
        if device_state_dict:
            device.state = DeviceState(**device_state_dict)
        return device